feat(Divider): rename isVertical to orientation
patternfly/pf-codemods pull request #177
Opened 2022-12-16 16:45 UTC by kmcfaul

Closes #149

2022-12-16 16:58 UTC, gitdallas requested changes
readme update, plus

2022-12-16 16:58 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/divider-remove-isVertical.js
> +      code: `import { Divider } from '@patternfly/react-core'; <Divider />`,
could add `orientation` here

2022-12-16 16:58 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/divider-remove-isVertical.js
> +      code: `<Divider />`,
same comment as on other pr, but this should actually test that your codemod doesn't touch non-pf components, so should have `isVertical` here

2022-12-16 19:05 UTC, gitdallas approved these changes

2022-12-22 18:53 UTC, jenny-s51 approved these changes

2023-01-03 14:08 UTC, merged