feat(accordion, expandablesection): rename displaySize prop value
patternfly/pf-codemods pull request #184
Opened 2022-12-20 18:38 UTC by jenny-s51

closes #138

2022-12-20 19:21 UTC, gitdallas requested changes

2022-12-20 19:21 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/accordion-rename-displaySize-large.js
> +      code: `import { Accordion } from '@patternfly/react-core'; <Accordion />`,
should test dislpaySize="lg" for new valid

2022-12-20 19:21 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/accordion-rename-displaySize-large.js
> +      code: `<Accordion displaySize />`,
should be displaySize="large" to test it won't affect nonpf

2022-12-20 19:21 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/expandable-section-rename-displaySize-large.js
> +  create: renameProp(
this is for renaming the property, not changing the property value

2023-01-03 16:18 UTC, gitdallas reviewed
Wonder if it we should create a renamePropValue helper function?

2023-01-04 19:29 UTC, gitdallas approved these changes

2023-01-09 20:42 UTC, thatblindgeye reviewed
Looks good! Just merge conflicts to resolve, and placing contents in the README alphabetically (could be worth doing in the index file as well)

2023-01-09 22:05 UTC, merged