feat(page components): remove sticky prop
patternfly/pf-codemods pull request #185
Opened 2022-12-22 18:37 UTC by jenny-s51

Closes:

- #151 
- #152 
- #153 
- #154

2023-01-04 19:40 UTC, gitdallas requested changes
to be full and match what we've done other places, think we should add the valid tests for more than just PageSection, and non-pf import tests.

if you want you could make the tests take less real estate (and quicker to glance at) by mapping `['PageSection', 'PageNavigation', etc..]` into the objects.

2023-01-09 20:39 UTC, thatblindgeye reviewed
Other than the above, the only nit I'd have is placing the addition to the README alphabetically.

2023-01-10 20:09 UTC, thatblindgeye approved these changes

2023-01-10 23:00 UTC, gitdallas approved these changes

2023-01-10 23:00 UTC, merged