chore(Masthead, PageHeader): component type default changed
patternfly/pf-codemods pull request #243
Opened 2023-02-07 18:10 UTC by kmcfaul

Closes: #242

2023-02-07 18:40 UTC, gitdallas requested changes
~~Aside from the typo below, do we really want to put a fixer in here?~~

~~If we are defaulting to switch based on other logic, why do we want to add `="a"`? I'm trying to understand but perhaps most the time we'd rather they didn't specify the value? Also, this might cause issues if they were previously using a different value for `component`/`logoComponent`?~~

Maybe the above paragraph doesn't matter as I see you are checking for whether the property exists, and then using the previous default.. and then this would serve as a note to let them change if they want.

2023-02-07 18:40 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/pageheader-update-logoComponent.js
> +                return fixer.insertTextAfter(node.name, ` component="a"`);
i think this is a copy/paste typo and should be logoComponent.

2023-02-08 14:14 UTC, gitdallas requested changes

2023-02-08 14:14 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/pageheader-update-logoComponent.js
> +      output: `import { PageHeader } from '@patternfly/react-core'; <PageHeader component="a" />`,
```suggestion
      output: `import { PageHeader } from '@patternfly/react-core'; <PageHeader logoComponent="a" />`,
```

2023-02-09 21:01 UTC, gitdallas approved these changes

2023-02-14 14:25 UTC, thatblindgeye approved these changes

2023-02-14 14:26 UTC, merged