feat(NotificationBadge): remove isRead prop
patternfly/pf-codemods pull request #247
Opened 2023-02-08 23:22 UTC by gitdallas

#223

2023-02-09 13:30 UTC, thatblindgeye approved these changes
🔥

2023-02-10 14:20 UTC, wise-king-sullyman approved these changes
LGTM, just needs conflicts resolved

2023-02-10 20:06 UTC, jenny-s51 requested changes
Nice @gitdallas , code looks and runs great! 👍 Just needs small update to link to the PR

2023-02-10 20:06 UTC, jenny-s51 commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/notificationBadge-remove-isRead.js
> +  // https://github.com/patternfly/patternfly-react/pull/8090
```suggestion
  // https://github.com/patternfly/patternfly-react/pull/8626
```

2023-02-10 20:06 UTC, jenny-s51 commented on packages/pf-codemods/README.md
> +### notificationBadge-remove-isRead [(#8090)](https://github.com/patternfly/patternfly-react/pull/8090)
```suggestion
### notificationBadge-remove-isRead [(#8626)](https://github.com/patternfly/patternfly-react/pull/8626)
```

2023-02-14 15:54 UTC, jenny-s51 approved these changes
👍

2023-02-14 15:54 UTC, merged