chore(Alert) replace titleHeadingLevel prop
patternfly/pf-codemods pull request #277
Opened 2023-02-16 13:52 UTC by Dominik-Petrik

closes #269

2023-02-16 15:55 UTC, gitdallas requested changes
lgtm, just some url typo in the comment

2023-02-22 18:59 UTC, gitdallas approved these changes

2023-02-22 19:42 UTC, thatblindgeye approved these changes

2023-02-22 19:44 UTC, jenny-s51 approved these changes
👌 Nice!

2023-02-22 19:45 UTC, merged