feat(DataList): added event param to callback
patternfly/pf-codemods pull request #306
Opened 2023-03-06 14:35 UTC by thatblindgeye

Closes #289 

The update made to SelectableRowObject in the linked PR for this codemod shouldn't be needed here, as https://github.com/patternfly/patternfly-react/issues/8423 will require a codemod that will handle that.

Also made an update to the onToggle codemod similar to this.

2023-03-06 15:19 UTC, gitdallas approved these changes

2023-03-06 23:24 UTC, thatblindgeye commented
@gitdallas for now I ust copy+pasted the logic from the onToggle codemod to the DataList one. I can do something similar to my other 2 open PRs. Figure we can create a possible helper as a followup.

2023-03-07 16:50 UTC, gitdallas requested changes
overall this is awesome, a few comments/nits

2023-03-07 16:50 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/onToggle-updated-paramaters.js
> +                node,
think we could strip this out to be reused? seems like it will be in several places already

2023-03-07 16:50 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/dataList-updated-callback.js
> +              ((type === "ArrowFunctionExpression" && params?.length === 1) ||
consider class level functions too for reporting, regardless of if we can apply a fixer

2023-03-07 16:50 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/test/rules/v5/onToggle-updated-paramaters.js
> +      code: `import { ${component} } from '@patternfly/react-core'; function onToggle() {}; <${component} onToggle={onToggle} />;`,
would we be able to ignore this case?

2023-03-07 17:23 UTC, gitdallas commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/onToggle-updated-paramaters.js
> +                node,
i see you left a comment regarding this, i'll leave that up to you

2023-03-07 19:25 UTC, wise-king-sullyman approved these changes
This is like magic

2023-03-07 19:36 UTC, thatblindgeye commented
@gitdallas @wise-king-sullyman refactored the logic in both codemods as a (currently very basic, specific) helper function. Should be a lot easier for similar codemods for adding that "event" param (or any param really, as long as its meant to be the first one).

Figure this could be a building block for more flexible things down the line

2023-03-07 19:39 UTC, wise-king-sullyman approved these changes
🔥 🔥 🔥 🔥 🔥

2023-03-07 20:29 UTC, merged