chore(Popover): renamed reference prop to triggerRef
patternfly/pf-codemods pull request #318
Opened 2023-03-06 20:04 UTC by adamviktora

Closes https://github.com/patternfly/pf-codemods/issues/296, relates to https://github.com/patternfly/patternfly-react/pull/8733

2023-03-08 02:47 UTC, gitdallas commented
according to comments on #314  perhaps we should combine these

2023-03-09 14:05 UTC, gitdallas requested changes
we can actually include this into a single rule file, similar to `toolbarVarious-remove-alignment` or `remove-removeFindDomNode`, then maybe just call it `various-rename-reference` for example.

2023-03-10 14:26 UTC, jenny-s51 approved these changes
Looks and runs great! Nice work @adamviktora 👍

2023-03-13 19:35 UTC, gitdallas approved these changes

2023-03-14 18:13 UTC, thatblindgeye approved these changes

2023-03-16 18:30 UTC, merged