chore(Pagination): rename ToggleTemplateProps
patternfly/pf-codemods pull request #320
Opened 2023-03-07 19:54 UTC by kmcfaul

Closes #305

* Checks imports to rename `ToggleTemplateProps` to `PaginationToggleTemplateProps`.
* Checks `toggleTemplate` prop and if it is passed a function, and that function has a type annotation, the annotation is also updated to `PaginationToggleTemplateProps`.

Put this in a separate rule tester than the current `pagination-remove-ToggleTemplateProps`. We might be able to remove the other rule but I left it in for now as it checks direct usage.

2023-03-08 14:46 UTC, gitdallas commented
Actually it looks like the previous PR (my own) was just wrong. Looks like I thought we were renaming a property rather than a type, and that property doesn't even exist. There is no `ToggleTemplateProps` or `PaginationToggleTemplateProps` on `Pagination`, only `toggleTemplate` which takes that type.

The old rule could be removed and the readme should be updated as well.

2023-03-08 19:33 UTC, gitdallas approved these changes
One thing I noticed is that with an alias import, this would basically remove the alias.

So `ToggleTemplateProps as TogProps ... : TogProps` would become `PaginationToggleTemplateProps ... : PaginationToggleTemplateProps`

I think this is pretty edge case-y though, and shouldn't break code so I'm not too concerned.

2023-03-08 21:39 UTC, jenny-s51 requested changes
This is awesome @kmcfaul LGTM 🎉 Just needs conflicts resolved, and left a small suggestion regarding verbiage. Should we also add a test case to `test.tsx`? I was able to test successfully with the inputs you added to the README!

2023-03-08 21:39 UTC, jenny-s51 commented on packages/pf-codemods/README.md
> +We've renamed the `ToggleTemplateProps` prop and to `PaginationToggleTemplateProps`.
Following @gitdallas 's comment above regarding how this wasn't a prop and is instead used as a type!
```suggestion
We've renamed `ToggleTemplateProps` to `PaginationToggleTemplateProps`.
```

2023-03-17 17:52 UTC, thatblindgeye approved these changes
Just needs a rebase

2023-03-21 20:35 UTC, jenny-s51 approved these changes

2023-03-21 20:35 UTC, merged