feat(DualListSelector) verify selected params have event param in the first place
patternfly/pf-codemods pull request #379
Opened 2023-04-06 11:52 UTC by Dominik-Petrik

closes #378

2023-04-12 18:06 UTC, thatblindgeye requested changes

2023-04-12 18:06 UTC, thatblindgeye commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/dualListSelector-update-onAvailableOptionsSearchInputChanged.js
> +  create: addCallbackParam(["DualListSelector"], { onAvailableOptionsSearchInputChanged: { defaultParamName: "_event", previousParamIndex: 1, otherMatchers: /^_?(ev\w*|e$)/ } }),
```suggestion
  create: addCallbackParam(["DualListSelector"], {
    onAvailableOptionsSearchInputChanged: {
      defaultParamName: "_event",
      previousParamIndex: 1,
      otherMatchers: /^_?(ev\w*|e$)/,
    },
    onChosenOptionsSearchInputChanged: {
      defaultParamName: "_event",
      previousParamIndex: 1,
      otherMatchers: /^_?(ev\w*|e$)/,
    },
    onListChange: "_event",
  }),
```

Then we can remove the other 2 rule files as well as 2 of the tester files. We should also update the file names to something like `dualListSelector-update-paramCallbacks`

2023-04-14 18:58 UTC, gitdallas approved these changes

2023-05-12 19:29 UTC, gitdallas commented
@Dominik-Petrik - conflicts

2023-05-15 18:46 UTC, merged