feat: No unused imports rule
patternfly/pf-codemods pull request #405
Opened 2023-04-17 13:23 UTC by adamviktora

Closes #397

Did some refactoring from the v4 rule:
- removing imports does not keep trailing commas, which were causing the file to by syntactically incorrect
- tokens are filtered with `JSXIdentifier` and `Identifier` types, so there are no misleadings, e.g. in this case: `<Title>Button</Title>` if there was an unused `Button` import, it was not removed in the previous version
- errors and fixes are more compact, 1 error and 1 group of fixes per package
- if there are no used imports from the package left, the whole import declaration is removed

2023-04-17 18:51 UTC, thatblindgeye requested changes

2023-04-17 18:51 UTC, thatblindgeye commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/no-unused-imports-v5.js
> +            };
Nit: `tokenAfter` instead of `nextComma`, since the token won't always be a comma

2023-04-19 11:39 UTC, adamviktora commented on packages/eslint-plugin-pf-codemods/lib/rules/v5/no-unused-imports-v5.js
> +            };
Yeah, good idea, I still had in mind removing the comma after specifier (which is necessary), but the semicolon seems to be the part of the node.

2023-04-24 14:30 UTC, gitdallas reviewed
If you'd like to not have leftover commas, here is code from one of my closed PRs awhile back that you might be able to use


	...specifiersToRemove.map( node => {
                const before = context.getTokenBefore(node);
                // checking against local as coming from the right, alias will show up first if exists and we want to recognize that
                const isImportBeforeFixed = specifiersToRemove.map(n => n.local?.name).includes(context.getTokenBefore(before)?.value);
                const after = context.getTokenAfter(node);
                let isRemainingImportsFixed = true;
                for(let n = after; n.value !== "}"; n = context.getTokenAfter(n)) {
                  if( n.type !== "Punctuator" && !specifiersToRemoveImportNameList.includes(n.value) ) {
                    isRemainingImportsFixed = false;
                    break;
                  }
                }
                let range = node.range;
                if (after.value === ',') {
                  range[1] = context.getTokenAfter(after).range[0];
                } 
                if (isRemainingImportsFixed && before.value === ',' && !isImportBeforeFixed) {
                  range[0] = context.getTokenBefore(before).range[1];
                }
                return fixer.replaceTextRange(range, '');
              })

2023-04-27 12:49 UTC, adamviktora commented
thanks for the comma-removing code, there is no problem with removing commas though, it should be handled by this code:

`          fix(fixer) {
            const getEndRange = (spec) => {
              const tokenAfter = sourceCode.getTokenAfter(spec);
              return tokenAfter.value === ","
                ? sourceCode.getTokenAfter(tokenAfter).range[0]
                : spec.range[1];
            };

            return unusedImports.length === node.specifiers.length
              ? fixer.remove(node)
              : unusedImports.map((spec) =>
                  fixer.removeRange([spec.range[0], getEndRange(spec)])
                );
          },`

2023-05-01 18:37 UTC, gitdallas commented
Just make sure that it would work with like... we are removing Foo, Bar, and Baz

tests:

- Foo, Bar, Baz
- Table, Foo, Button, Bar, OptionList, Baz

i think with the code above, `Foo, Bar, Baz` might run into "overlap" issues (feel like i've got that in the past trying something like that).

2023-05-03 14:34 UTC, gitdallas commented
@thatblindgeye @thatblindgeye @jenny-s51 - what do you guys think about taking this out of `beta` list and putting it into `cleanup`? any reason not to?

2023-05-03 14:39 UTC, jenny-s51 reviewed
@gitdallas I agree this would make sense as a cleanup rule

2023-05-03 15:38 UTC, thatblindgeye commented
@gitdallas Seems like it works fine when testing with the empty state fixes (since that had given us issues when trying to apply fixes).

2023-05-04 13:00 UTC, adamviktora commented
> Just make sure that it would work with like... we are removing Foo, Bar, and Baz
> 
> tests:
> 
>     * Foo, Bar, Baz
> 
>     * Table, Foo, Button, Bar, OptionList, Baz
> 
> 
> i think with the code above, `Foo, Bar, Baz` might run into "overlap" issues (feel like i've got that in the past trying something like that).

Tried these and other cases, works fine - when all imports from the current source package are unused, it removes the whole import.

2023-05-04 14:36 UTC, gitdallas requested changes

2023-05-04 14:36 UTC, gitdallas commented on packages/pf-codemods/README.md
> +This rule removes all unused imports from `patternfly/react` packages. It is a special rule which will not run by default. It should be run after all the other rules as a final cleanup using the opti
will need to update this now that it's in cleanup rather than beta

2023-05-04 16:59 UTC, merged