fix(úAdd callback param fix
patternfly/pf-codemods pull request #521
Opened 2023-06-12 16:28 UTC by adamviktora

Closes #520

2023-06-12 17:28 UTC, thatblindgeye requested changes

2023-06-12 17:40 UTC, gitdallas requested changes
looks good for the most part. in addition to addressing eric, please add testing

2023-06-13 12:47 UTC, thatblindgeye approved these changes

2023-06-13 20:17 UTC, gitdallas commented
he's planning to take a crack at the state hooks

2023-06-14 18:08 UTC, gitdallas reviewed
i know you're still working on something.. but it's looking pretty good so far, i had a couple comments

2023-06-15 14:16 UTC, gitdallas commented
@thatblindgeye @wise-king-sullyman  - rerequest as new changes are fairly big

2023-06-15 17:28 UTC, thatblindgeye requested changes
In addition to the Slack convo regarding the state setter fix not working for codemods that are swapping events (rather than adding them):

- We'll need to update the examples in the README since all of them will now be incorrect with this update
- Not a blocker since we can do a followup for it if needed, but it'd be nice to add more comments for the tests being pushed in the testHelpers file so we can keep track of what's already been added, maybe also sorting the tests a bit

2023-06-15 17:35 UTC, wise-king-sullyman commented on packages/eslint-plugin-pf-codemods/lib/helpers.js
> +                  ) {
Or alternatively to comments, try to just refactor some of these conditionals to be variables with names that make the code more self documenting. Not that I'm against comments though.

2023-06-15 19:52 UTC, wise-king-sullyman approved these changes
Nothing I'd block over at this point.

2023-06-16 11:49 UTC, adamviktora commented
Thanks for the update Austin!

2023-06-16 12:38 UTC, thatblindgeye approved these changes
If we want to get the actual code updates in ASAP then this is looking good, we can do a followup to update examples in the README

2023-06-16 17:22 UTC, wise-king-sullyman commented
Addressing README updates in a followup would be my recommendation since we can communicate this change to our testers directly. Just need the README changes done before we go GA IMO.

2023-06-16 17:47 UTC, gitdallas approved these changes

2023-06-16 17:48 UTC, merged