feat(Nav): props updates
patternfly/pf-codemods pull request #585
Opened 2024-02-21 15:39 UTC by adamviktora

Closes #547

2024-02-21 20:55 UTC, thatblindgeye requested changes

2024-02-21 20:55 UTC, thatblindgeye commented on packages/eslint-plugin-pf-codemods/src/rules/v6/navRemoveTertiaryVariant/nav-remove-tertiary-variant.test.ts
> +      code: `<Nav variant />`,
```suggestion
      code: `<Nav variant="tertiary" />`,
```

2024-02-22 21:25 UTC, wise-king-sullyman approved these changes

2024-02-27 13:09 UTC, thatblindgeye approved these changes

2024-02-27 18:39 UTC, merged