feat(DataListAction): Remove isPlainButtonAction prop
patternfly/pf-codemods pull request #775
Opened 2024-09-20 16:27 UTC by tlabaj

Closes: #768

2024-09-23 15:07 UTC, adamviktora reviewed
Looks like there is accidentally a `.history` folder commited.

Other than that and a comment bellow LGTM

2024-09-23 15:07 UTC, adamviktora commented on packages/eslint-plugin-pf-codemods/src/rules/v6/dataListActionRemoveIsPlainButtonActionProp/dataListActionRemoveIsPlainButtonActionPropInput.tsx
> +  <DataListAction  />
The `isPlainButtonAction` prop is missing here

2024-09-24 12:02 UTC, thatblindgeye requested changes

2024-09-24 18:15 UTC, thatblindgeye approved these changes

2024-09-25 09:22 UTC, adamviktora approved these changes

2024-09-25 15:51 UTC, merged